apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mosso\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mosso\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/servicestation-servicestationnetwork: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - image: apigateway
          name: api-gateway
          ports:
            - containerPort: 80
              hostPort: 2000
              protocol: TCP
            - containerPort: 443
              hostPort: 2001
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
