apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
  namespace: default
spec:
  ports:
    - name: "2000"
      port: 2000
      targetPort: 80
    - name: "2001"
      port: 2001
      targetPort: 443
  selector:
    io.kompose.service: apigateway
status:
  loadBalancer: {}
