apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mosso\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: taskmanagerformechanicdatabase
  name: taskmanagerformechanicdatabase
  namespace: default
spec:
  ports:
    - name: "1423"
      port: 1423
      targetPort: 1433
  selector:
    io.kompose.service: taskmanagerformechanicdatabase
status:
  loadBalancer: {}
