apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mosso\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: taskmanagerformechanic-web
  name: taskmanagerformechanic-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taskmanagerformechanic-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mosso\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/servicestation-servicestationnetwork: "true"
        io.kompose.service: taskmanagerformechanic-web
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: MechanicAPIDatabase
            - name: DB_NAME
              value: ServiceStation
            - name: DB_SA_PASSWORD
              value: Qwerty123
            - name: RBBITMQ_PASS
              value: ' guest'
            - name: RBBITMQ_USER
              value: ' guest'
          image: taskmanagerformechanicweb
          name: mechanicapi
          ports:
            - containerPort: 80
              hostPort: 2020
              protocol: TCP
            - containerPort: 443
              hostPort: 2021
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
